Repository SmingHub/Sming, pull requests merged in 2019-06, with the labels that each got.

#1714 Added script to help setup tap0 on Linux.
  Sming/Arch/Host/Tools/setup-network-linux.sh
Labels: 3 - Review

#1716 Don't use buffer for outgoing data. Otherwise we will end up with dou…
  Sming/Core/Network/Http/HttpResponse.cpp
Labels: Port-to-LTS

#1721 Add additional checks to `Vector` class methods
  Sming/Wiring/WVector.h
Labels: 3 - Review

#1726 Use explicit signed types in base64_decode
  Sming/Components/libb64/cdecode.c
Labels: 0 - Backlog, Port-to-LTS

#1729 Wemos D1 mini has pin 16, so change test to allow 16 as a valid pin
  Sming/Arch/Host/Core/Digital.cpp
Labels: Port-to-LTS
