Repository SmingHub/Sming, pull requests merged in 2019-11, with the labels that each got.

#1957 CStringArray improvements
  Sming/Core/Data/CStringArray.cpp
  Sming/Core/Data/CStringArray.h
  Sming/System/include/stringutil.h
  Sming/System/stringutil.cpp
  Sming/Wiring/WString.cpp
  Sming/Wiring/WString.h
  tests/HostTests/app/modules.h
  tests/HostTests/app/test-cstringarray.cpp
Labels: Port-to-LTS

#1951 Implement Small String Optimisation (SSO)
  Sming/Arch/Host/Components/libc/memrchr.c
  Sming/Core/Data/CStringArray.cpp
  Sming/System/include/stringutil.h
  Sming/Wiring/WString.cpp
  Sming/Wiring/WString.h
  tests/HostTests/app/arduino-test-string.cpp
Labels: 0 - Backlog

#1965 Adding precaching from Arduino for ESP8266.
  Sming/Arch/Esp8266/Components/spi_flash/README.rst
  Sming/Arch/Esp8266/Components/spi_flash/api.rst
  Sming/Arch/Esp8266/Components/spi_flash/include/iram_precache.h
  Sming/Arch/Esp8266/Components/spi_flash/iram_precache.cpp
  Sming/Arch/Esp8266/Components/spi_flash/precache.rst
  Sming/Arch/Host/Components/spi_flash/include/iram_precache.h
  docs/source/information/memory.rst
  tests/HostTests/app/modules.h
  tests/HostTests/app/test-http.cpp
  tests/HostTests/app/test-objectmap.cpp
  tests/HostTests/app/test-precache.cpp
  tests/HostTests/app/test-serial.cpp
  tests/HostTests/app/test-url.cpp
Labels: 3 - Review
