Repository SmingHub/Sming, pull requests merged in 2019-07, with the labels that each got.

#1736 Improve Host `make run` behaviour
  Sming/Arch/Host/Components/driver/component.mk
  Sming/Arch/Host/Components/esp_wifi/component.mk
  Sming/Arch/Host/Components/gdbstub/component.mk
  Sming/Arch/Host/Components/vflash/component.mk
  Sming/Arch/Host/app.mk
  Sming/Arch/Host/build.mk
  Sming/Arch/Host/readme.md
  samples/Basic_DateTime/component.mk
  samples/Basic_Serial/component.mk
  samples/Basic_rBoot/component.mk
  samples/LiveDebug/component.mk
  tests/HostTests/component.mk
Labels: 3 - Review

#1742 Fix memory leak in MqttClient
  Sming/Core/Network/MqttClient.cpp
  Sming/Core/Network/MqttClient.h
Labels: 0 - Backlog, Port-to-LTS

#1761 Decrease latency in MqttClient publishing.
  Sming/Core/Network/MqttClient.cpp
  Sming/Core/Network/TcpClient.cpp
  Sming/Core/Network/TcpConnection.cpp
Labels: Port-to-LTS

#1768 Fix line-ending problems
  .gitattributes
  Sming/Arch/Host/Components/heap/component.mk
  Sming/Arch/Host/Components/lwip/Windows/.gitignore
  Sming/Components/malloc_count/component.mk
  Sming/Components/spiffs/spiffs.patch
  Sming/Libraries/.patches/Adafruit_BME280_Library.patch
  Sming/Libraries/.patches/Adafruit_ST7735.patch
  Sming/Libraries/.patches/ITEADLIB_Arduino_Nextion.patch
  Sming/Libraries/.patches/TM1637.patch
  Sming/Makefile
  samples/Basic_Delegates/app/callbacks.cpp
  samples/Basic_Delegates/app/callbacks.h
  samples/Basic_Delegates/app/speed.cpp
  samples/Basic_WebSkeletonApp_LTS/.project
  tests/HostTests/app/test-json5.cpp
Labels: 3 - Review

#1785 Fix CStringArray edge case
  Sming/Core/Data/CStringArray.cpp
Labels: Port-to-LTS
