Repository SmingHub/Sming, pull requests merged in 2020-11, with the labels that each got.

#2132 HttpClient improvements. Added support for servers that do not support connection reuse.
  Sming/Core/Network/Http/HttpClientConnection.cpp
  Sming/Core/Network/Http/HttpClientConnection.h
  Sming/Core/Network/Http/HttpCommon.h
  Sming/Core/Network/HttpClient.cpp
  Sming/Core/Network/HttpClient.h
  Sming/Core/Network/TcpClient.cpp
  Sming/Core/Network/TcpClient.h
  Sming/Core/Network/TcpConnection.cpp
  Sming/Core/Network/TcpConnection.h
Labels: 3 - Review

#2142 Prefer `using` to typedef; Consistent enum/struct declarations
  Sming/Arch/Esp32/Platform/RTC.cpp
  Sming/Arch/Esp8266/Platform/RTC.cpp
  Sming/Arch/Host/Core/pins_arduino.h
  Sming/Core/AtClient.h
  Sming/Core/CallbackTimer.h
  Sming/Core/Data/StreamTransformer.h
  Sming/Core/DateTime.h
  Sming/Core/Debug.h
  Sming/Core/FileSystem.h
  Sming/Core/HardwareSerial.h
  Sming/Core/Interrupts.h
  Sming/Core/Network/Http/HttpBodyParser.cpp
  Sming/Core/Network/Http/HttpBodyParser.h
  Sming/Core/Network/Http/HttpClientConnection.h
  Sming/Core/Network/Http/HttpCommon.h
  Sming/Core/Network/Http/HttpRequest.h
  Sming/Core/Network/Http/HttpResource.h
  Sming/Core/Network/Http/HttpResourceTree.h
  Sming/Core/Network/Http/HttpServerConnection.h
  Sming/Core/Network/Http/Websocket/WebsocketConnection.h
  Sming/Core/Network/HttpClient.h
  Sming/Core/Network/HttpServer.h
  Sming/Core/Network/Mqtt/MqttPayloadParser.h
  Sming/Core/Network/MqttClient.h
  Sming/Core/Network/NtpClient.h
  Sming/Core/Network/SmtpClient.h
  Sming/Core/Network/TcpClient.h
  Sming/Core/Network/TcpConnection.h
  Sming/Core/Network/TcpServer.h
  Sming/Core/Network/TelnetServer.h
  Sming/Core/Network/UdpConnection.h
  Sming/Libraries/MultipartParser/src/HttpMultipartResource.h
  Sming/Libraries/OtaUpgrade/OtaUpgrade/BasicStream.h
  Sming/Libraries/OtaUpgrade/OtaUpgrade/ChecksumVerifier.h
  Sming/Libraries/OtaUpgrade/OtaUpgrade/FileFormat.h
  Sming/Platform/BssInfo.h
  Sming/Platform/OsMessageInterceptor.h
  Sming/Platform/Station.h
  Sming/Platform/System.h
  Sming/Platform/WifiEvents.h
  Sming/Platform/WifiSniffer.h
  Sming/Services/CommandProcessing/CommandDelegate.h
  Sming/Services/CommandProcessing/CommandHandler.h
  Sming/System/include/gdb/gdb_syscall.h
  Sming/System/include/m_printf.h
  Sming/Wiring/IpAddress.h
  Sming/Wiring/MacAddress.h
  Sming/Wiring/WConstants.h
  Sming/Wiring/WHashMap.h
  Sming/Wiring/WString.h
  Sming/Wiring/WVector.h
  Sming/Wiring/wiring_private.h
  docs/source/contribute/clang-tools.rst
  docs/source/contribute/coding-style.rst
  docs/source/experimental/signed-ota.rst
  samples/Basic_Delegates/app/speed.cpp
  samples/Basic_Serial/include/SerialReadingDelegateDemo.h
  tests/HostTests/app/test-rational.cpp
Labels: 0 - Backlog

#2153 Allocate LimitedMemoryStream buffer on demand and not upfront.
  Sming/Core/Data/Stream/LimitedMemoryStream.cpp
  Sming/Core/Data/Stream/LimitedMemoryStream.h
Labels: 0 - Backlog

#2155 GCC compilers version 8 or newer are highly recommended.
  README.md
  Sming/Arch/Esp8266/build.mk
  Sming/Arch/Host/build.mk
  Sming/build.mk
  docs/source/arch/esp8266/getting-started/eqt.rst
  docs/source/arch/esp8266/getting-started/macos.rst
  docs/source/arch/host/host-emulator.rst
Labels: 3 - Review

#2157 MqttClient revisions
  Sming/Core/Network/MqttClient.cpp
  Sming/Core/Network/MqttClient.h
  samples/MqttClient_Hello/app/application.cpp
Labels: 0 - Backlog, 3 - Review

#2149 [WIP] Connecting to Amazon Web Services
  samples/Basic_AWS/.cproject
  samples/Basic_AWS/.project
  samples/Basic_AWS/Makefile
  samples/Basic_AWS/README.rst
  samples/Basic_AWS/app/MqttMessage.h
  samples/Basic_AWS/app/application.cpp
  samples/Basic_AWS/component.mk
  samples/Basic_AWS/files/3051d5b002-certificate.pem.crt.txt
  samples/Basic_AWS/files/3051d5b002-private.pem.key
  samples/Basic_AWS/files/3051d5b002-public.pem.key
  samples/Basic_AWS/files/AmazonRootCA1.pem
  samples/Basic_AWS/files/AmazonRootCA1.pem.der
  samples/Basic_AWS/files/certificate.pem.crt.der
  samples/Basic_AWS/files/endpoint.txt
  samples/Basic_AWS/files/private.pem.key.der
  samples/Basic_AWS/include/ssl/cert.h
  samples/Basic_AWS/include/ssl/private_key.h
Labels: 3 - Review
