Repository SmingHub/Sming, pull requests merged in 2020-12, with the labels that each got.

#2159 Don't enqueue nullptr streams.
  Sming/Core/Data/Stream/StreamChain.h
Labels: 3 - Review

#2165 CString fixes
  Sming/Core/Data/CString.h
Labels: 3.5 - Approved - Waiting for CI results

#2166 Fix various issues identified by codacy
  Sming/Arch/Esp8266/Components/spi_flash/flashmem.c
  Sming/Core/Network/Http/HttpRequestAuth.cpp
  Sming/Core/SystemClock.cpp
  Sming/Services/CommandProcessing/CommandHandler.h
Labels: 3.5 - Approved - Waiting for CI results

#2164 Add dataset templating support
  Sming/Core/Data/Format.h
  Sming/Core/Data/Format/Formatter.h
  Sming/Core/Data/Format/Html.cpp
  Sming/Core/Data/Format/Html.h
  Sming/Core/Data/Format/Json.cpp
  Sming/Core/Data/Format/Json.h
  Sming/Core/Data/Format/Standard.cpp
  Sming/Core/Data/Format/Standard.h
  Sming/Core/Data/Stream/SectionStream.cpp
  Sming/Core/Data/Stream/SectionStream.h
  Sming/Core/Data/Stream/SectionTemplate.cpp
  Sming/Core/Data/Stream/SectionTemplate.h
  Sming/Core/Data/Stream/TemplateStream.cpp
  Sming/Core/Data/Stream/TemplateStream.h
  tests/HostTests/app/resource.cpp
  tests/HostTests/include/modules.h
  tests/HostTests/include/resource.h
  tests/HostTests/modules/Stream.cpp
  tests/HostTests/modules/TemplateStream.cpp
  tests/HostTests/resource/unit_testing.html
  tests/HostTests/resource/unit_testing.rst
  tests/HostTests/resource/ut_template1.in.rst
  tests/HostTests/resource/ut_template1.out1.rst
  tests/HostTests/resource/ut_template2.in.rst
Labels: 3.5 - Approved - Waiting for CI results

#2167 Add iterator support for HashMap and Vector, with basic tests
  Sming/Wiring/WHashMap.h
  Sming/Wiring/WVector.h
  tests/HostTests/include/modules.h
  tests/HostTests/modules/Wiring.cpp
Labels: 3.5 - Approved - Waiting for CI results

#2168 Fix 'Multiple matches found for Component XXX' warning
  Sming/project.mk
Labels: 3.5 - Approved - Waiting for CI results

#2170 Fix LimitedMemoryStream::isFinished()
  Sming/Core/Data/Stream/LimitedMemoryStream.h
Labels: 3.5 - Approved - Waiting for CI results

#2163 HTTP client fixes
  Sming/Core/Data/Stream/MultipartStream.cpp
  Sming/Core/Data/Stream/MultipartStream.h
  Sming/Core/Network/Http/HttpClientConnection.cpp
  Sming/Core/Network/Http/HttpClientConnection.h
  Sming/Core/Network/Http/HttpConnection.cpp
  Sming/Core/Network/Http/HttpRequest.h
  Sming/Core/Network/MqttClient.cpp
  Sming/Core/Network/TcpConnection.cpp
  Sming/Core/Network/TcpConnection.h
Labels: 3.5 - Approved - Waiting for CI results

#2174 CS5460 library updates
  Sming/Libraries/CS5460/README.rst
  Sming/Libraries/CS5460/samples/generic/app/application.cpp
Labels: 3 - Review

#2173 HttpClient: SSL adjustments
  samples/HttpClient/app/application.cpp
  samples/HttpClient/component.mk
Labels: 3 - Review

#2178 Fixed issues in toString methods in:
  Sming/Core/Network/Http/HttpRequest.cpp
  Sming/Core/Network/Http/HttpResponse.cpp
Labels: 3 - Review

#2180 Fix CI toolchains
  .appveyor/install.cmd
  .travis.yml
  Sming/Arch/Esp32/Tools/travis/install.sh
  Sming/Arch/Esp8266/Components/esp-open-lwip/esp-open-lwip.patch
  Sming/Arch/Esp8266/Components/gdbstub/gdbhostio.cpp
  Sming/Arch/Esp8266/Components/gdbstub/gdbstub.cpp
  Sming/Arch/Esp8266/Components/gdbstub/gdbsyscall.cpp
  Sming/Arch/Esp8266/Components/heap/custom_heap.c
  Sming/Arch/Esp8266/Tools/travis/build.run.sh
  Sming/Arch/Esp8266/Tools/travis/install.sh
  Sming/Arch/Esp8266/build.mk
  Sming/Arch/Host/Components/gdbstub/gdb_syscall.cpp
  Sming/Components/axtls-8266/axtls-8266.patch
  Sming/Components/axtls-8266/component.mk
  Sming/Platform/OsMessageInterceptor.cpp
  Sming/Platform/OsMessageInterceptor.h
  Sming/Wiring/FakePgmSpace.h
  Sming/build.mk
  Sming/component-wrapper.mk
  appveyor.yml
  docs/source/arch/esp8266/getting-started/eqt.rst
  docs/source/arch/esp8266/getting-started/linux.rst
  docs/source/arch/esp8266/getting-started/macos.rst
  docs/source/arch/esp8266/getting-started/windows-manual.rst
  tests/HostTests/modules/TemplateStream.cpp
Labels: 3.5 - Approved - Waiting for CI results

#2185 CodeQL changes to fix the failing C/C++ analyzer.
  .github/workflows/codeql-analysis.yml
Labels: 3 - Review

#2130 Revisions to SPI classes
  Sming/Arch/Esp32/Core/SPI.cpp
  Sming/Arch/Esp32/Core/SPI.h
  Sming/Arch/Esp32/Core/SPISoft.cpp
  Sming/Arch/Esp8266/Core/SPI.cpp
  Sming/Arch/Esp8266/Core/SPI.h
  Sming/Arch/Esp8266/Core/SPISoft.cpp
  Sming/Arch/Host/Core/SPI.h
  Sming/Core/SPI.h
  Sming/Core/SPIBase.h
  Sming/Core/SPISettings.h
  Sming/Core/SPISoft.h
  Sming/Libraries/Adafruit_GFX/Adafruit_GFX.cpp
  Sming/Libraries/Adafruit_GFX/Adafruit_GFX.h
  Sming/Libraries/Adafruit_ILI9341/Adafruit_ILI9341.cpp
  Sming/Libraries/Adafruit_ILI9341/Adafruit_ILI9341.h
  Sming/Libraries/Adafruit_ILI9341/README.md
  Sming/Libraries/Adafruit_ILI9341/README.rst
  Sming/Libraries/Adafruit_ILI9341/component.mk
  Sming/Libraries/Adafruit_ILI9341/hspi.c
  Sming/Libraries/Adafruit_ILI9341/hspi.h
  Sming/Libraries/Adafruit_ILI9341/spi_register.h
  Sming/Libraries/RF24/RF24.cpp
  Sming/Libraries/RF24/RF24_config.h
  Sming/Libraries/SDCard/SDCard.cpp
  Sming/Libraries/SDCard/SDCard.h
  Sming/component.mk
  samples/Arducam/app/application.cpp
  samples/CanBus/app/application.cpp
  samples/Radio_nRF24L01/app/application.cpp
  samples/Radio_nRF24L01/component.mk
  samples/SDCard/app/application.cpp
  samples/SDCard/component.mk
Labels: 0 - Backlog, 3 - Review
