Repository SmingHub/Sming, pull requests merged in 2021-05, with the labels that each got.

#2322 Fixes to Travis CI
  .travis.yml
  Tools/install.sh
  Tools/travis/install.sh
Labels: 3.5 - Approved - Waiting for CI results

#2327 Store the actual size of the downloaded rBoot item.
  Sming/Components/rboot/src/Network/RbootHttpUpdater.cpp
Labels: 3 - Review, Port-to-LTS

#2331 Add ESP8266 implementations for all STL exception functions
  Sming/Arch/Esp8266/Components/esp8266/esp_cplusplus.cpp
  Sming/Arch/Esp8266/Components/esp8266/functexcept.cpp
Labels: 3 - Review

#2332 Feature: unified Over-The-Air (OTA) upgrades
  README.md
  Sming/Arch/Esp32/spiffs-two-roms.hw
  Sming/Arch/Esp8266/spiffs-two-roms.hw
  Sming/Components/Ota/README.rst
  Sming/Components/Ota/component.mk
  Sming/Components/Ota/src/.cs
  Sming/Components/Ota/src/Arch/Esp32/IdfUpgrader.cpp
  Sming/Components/Ota/src/Arch/Esp32/include/Ota/IdfUpgrader.h
  Sming/Components/Ota/src/Arch/Esp32/include/Ota/Upgrader.h
  Sming/Components/Ota/src/Arch/Esp8266/RbootUpgrader.cpp
  Sming/Components/Ota/src/Arch/Esp8266/include/Ota/RbootUpgrader.h
  Sming/Components/Ota/src/Arch/Esp8266/include/Ota/Upgrader.h
  Sming/Components/Ota/src/Manager.cpp
  Sming/Components/Ota/src/UpgradeOutputStream.cpp
  Sming/Components/Ota/src/include/Ota/Manager.h
  Sming/Components/Ota/src/include/Ota/UpgradeOutputStream.h
  Sming/Components/Ota/src/include/Ota/UpgraderBase.h
  Sming/Components/OtaNetwork/README.rst
  Sming/Components/OtaNetwork/component.mk
  Sming/Components/OtaNetwork/src/.cs
  Sming/Components/OtaNetwork/src/HttpUpgrader.cpp
  Sming/Components/OtaNetwork/src/include/Ota/Network/HttpUpgrader.h
  Sming/Libraries/OtaUpgrade/OtaUpgrade/BasicStream.cpp
  Sming/Libraries/OtaUpgrade/OtaUpgrade/BasicStream.h
  Sming/Libraries/OtaUpgrade/component.mk
  Sming/Libraries/OtaUpgradeMqtt/component.mk
  Sming/Libraries/OtaUpgradeMqtt/samples/Upgrade/app/application.cpp
  Sming/Libraries/OtaUpgradeMqtt/samples/Upgrade/component.mk
  Sming/Libraries/OtaUpgradeMqtt/samples/Upgrade/ota.hw
  Sming/Libraries/OtaUpgradeMqtt/src/RbootPayloadParser.cpp
  Sming/Libraries/OtaUpgradeMqtt/src/StandardPayloadParser.cpp
  Sming/Libraries/OtaUpgradeMqtt/src/include/OtaUpgrade/Mqtt/RbootPayloadParser.h
  Sming/Libraries/OtaUpgradeMqtt/src/include/OtaUpgrade/Mqtt/StandardPayloadParser.h
  docs/source/getting-started/index.rst
  samples/Basic_Ota/.cproject
  samples/Basic_Ota/.project
  samples/Basic_Ota/Makefile
  samples/Basic_Ota/README.rst
  samples/Basic_Ota/app/application.cpp
  samples/Basic_Ota/component.mk
  samples/Basic_Ota/files/testfile.txt
  samples/Basic_Ota/ota.hw
  samples/Basic_rBoot/README.rst
  samples/Basic_rBoot/basic_rboot.hw
  samples/Basic_rBoot/component.mk
Labels: 3.5 - Approved - Waiting for CI results
