Repository SmingHub/Sming, pull requests merged in 2021-11, with the labels that each got.

#2410 Fix `make ide-vscode` for Esp32/Windows
  Sming/Arch/Esp32/Components/sming-arch/component.mk
  Sming/Arch/Host/build.mk
  Sming/System/include/gdb/gdb_hooks.h
  Sming/build.mk
  Sming/project.mk
  Sming/util.mk
  Tools/ide/common/sming.py
  Tools/ide/vscode/setup.py
  Tools/ide/vscode/template/intellisense/configuration.json
  Tools/ide/vscode/template/launch.json
  Tools/ide/vscode/template/tasks.json
  Tools/ide/vscode/template/workspace.json
  docs/Makefile
  docs/source/tools/vscode.rst
Labels: 3.5 - Approved - Waiting for CI results

#2411 Fix minor warnings
  Sming/Arch/Esp32/Core/Digital.cpp
  Sming/Core/Data/LinkedObjectList.h
  Sming/Libraries/OtaUpgradeMqtt/samples/Upgrade/app/application.cpp
  Sming/Libraries/OtaUpgradeMqtt/src/StandardPayloadParser.cpp
Labels: 3.5 - Approved - Waiting for CI results

#2416 Fix issue with wrong parameter count during deployment.
  Sming/Libraries/OtaUpgradeMqtt/src/PayloadParser.cpp
  Sming/Libraries/OtaUpgradeMqtt/tools/deployer/app/application.cpp
  Sming/Libraries/OtaUpgradeMqtt/tools/deployer/component.mk
Labels: Port-to-LTS

#2423 Specify C compiler to use for lwip host
  Sming/Arch/Host/Components/lwip/component.mk
Labels: 3.5 - Approved - Waiting for CI results

#2424 HttpServer: Fixed a bug with request headers not being reset.
  Sming/Components/Network/src/Network/Http/HttpRequest.cpp
  Sming/Components/Network/src/Network/Http/HttpServerConnection.cpp
  samples/HttpServer_Plugins/app/application.cpp
Labels: Port-to-LTS, 3.5 - Approved - Waiting for CI results

#2426 Fixed a bug with request headers not being reset. (#2424)
  Sming/Core/Network/Http/HttpRequest.cpp
  Sming/Core/Network/Http/HttpServerConnection.cpp
Labels: 3.5 - Approved - Waiting for CI results
