Repository SmingHub/Sming, pull requests merged in 2021-03, with the labels that each got.

#2249 Add setMacAddress() method to Station and AccessPoint
  Sming/Arch/Esp32/Platform/AccessPointImpl.cpp
  Sming/Arch/Esp32/Platform/AccessPointImpl.h
  Sming/Arch/Esp32/Platform/StationImpl.cpp
  Sming/Arch/Esp32/Platform/StationImpl.h
  Sming/Arch/Esp8266/Platform/AccessPointImpl.cpp
  Sming/Arch/Esp8266/Platform/AccessPointImpl.h
  Sming/Arch/Esp8266/Platform/StationImpl.cpp
  Sming/Arch/Esp8266/Platform/StationImpl.h
  Sming/Arch/Host/Platform/AccessPointImpl.cpp
  Sming/Arch/Host/Platform/AccessPointImpl.h
  Sming/Arch/Host/Platform/StationImpl.cpp
  Sming/Arch/Host/Platform/StationImpl.h
  Sming/Platform/AccessPoint.h
  Sming/Platform/Station.h
Labels: 3.5 - Approved - Waiting for CI results

#2263 Storage improvements
  Sming/Arch/Esp32/Components/spi_flash/flashmem.cpp
  Sming/Arch/Esp32/Components/spi_flash/include/esp_spi_flash.h
  Sming/Arch/Esp32/standard.hw
  Sming/Arch/Host/app.mk
  Sming/Components/Storage/Tools/hwconfig/config.py
  Sming/Components/Storage/src/Iterator.cpp
  Sming/Components/Storage/src/SpiFlash.cpp
  Sming/Components/Storage/src/include/Storage/Device.h
  Sming/Components/Storage/src/include/Storage/SpiFlash.h
  Sming/Components/rboot/component.mk
  samples/Basic_Storage/app/application.cpp
  samples/Basic_Storage/basic_storage.hw
  samples/Basic_rBoot/app/application.cpp
  samples/Basic_rBoot/component.mk
  tests/HostTests/modules/Spiffs.cpp
Labels: 3.5 - Approved - Waiting for CI results

#2267 Fix handling of `HWCONFIG_OPTS`
  Sming/Components/Storage/Tools/hwconfig/config.py
  Sming/Components/Storage/Tools/hwconfig/partition.py
Labels: 3 - Review

#2274 Add graphical hardware profile editor
  Sming/Arch/Esp8266/Components/esp8266/component.mk
  Sming/Components/Storage/Tools/hwconfig/common.py
  Sming/Components/Storage/Tools/hwconfig/config.py
  Sming/Components/Storage/Tools/hwconfig/editor.py
  Sming/Components/Storage/Tools/hwconfig/hwconfig.py
  Sming/Components/Storage/Tools/hwconfig/partition.py
  Sming/Components/Storage/Tools/hwconfig/storage.py
  Sming/Components/Storage/component.mk
  Sming/Components/rboot/component.mk
  Sming/Components/spiffs/component.mk
  Sming/building.rst
  Sming/project.mk
Labels: 3.5 - Approved - Waiting for CI results

#2278 Fixed publishing MQTT messages having a stream as payload.
  Sming/Core/Network/MqttClient.cpp
Labels: 3 - Review, Port-to-LTS

#2283 Base64 size calculations wrong
  Sming/Core/Network/WebHelpers/base64.cpp
Labels: Port-to-LTS

#2280 Fix SMTP issues
  Sming/Components/ssl/src/Session.cpp
  Sming/Core/Network/SmtpClient.cpp
  Sming/Core/Network/SmtpClient.h
Labels: 3.5 - Approved - Waiting for CI results, Port-to-LTS

#2289 Allow control over host debug messages
  Sming/Arch/Host/Components/driver/hw_timer.cpp
  Sming/Arch/Host/Components/driver/uart_server.cpp
  Sming/Arch/Host/Components/esp_hal/tasks.cpp
  Sming/Arch/Host/Components/hostlib/hostmsg.c
  Sming/Arch/Host/Components/hostlib/hostmsg.h
  Sming/Arch/Host/Components/hostlib/options.h
  Sming/Arch/Host/Components/hostlib/sockets.cpp
  Sming/Arch/Host/Components/hostlib/startup.cpp
  Sming/Arch/Host/Components/lwip/Linux/host_lwip.c
  Sming/Arch/Host/Components/lwip/Windows/host_lwip.c
  Sming/Arch/Host/Components/spi_flash/flashmem.cpp
  Sming/Arch/Host/Platform/StationImpl.cpp
  Sming/Components/rboot/src/Arch/Host/rboot.cpp
  samples/Basic_Utility/README.rst
Labels: 3.5 - Approved - Waiting for CI results

#2269 Firmware update via MQTT
  README.md
  Sming/Arch/Host/Components/hostlib/startup.cpp
  Sming/Arch/Host/spiffs-two-roms.hw
  Sming/Libraries/OtaUpgradeMqtt/.cs
  Sming/Libraries/OtaUpgradeMqtt/README.rst
  Sming/Libraries/OtaUpgradeMqtt/api.rst
  Sming/Libraries/OtaUpgradeMqtt/component.mk
  Sming/Libraries/OtaUpgradeMqtt/samples/Upgrade/.cproject
  Sming/Libraries/OtaUpgradeMqtt/samples/Upgrade/.cs
  Sming/Libraries/OtaUpgradeMqtt/samples/Upgrade/.gitignore
  Sming/Libraries/OtaUpgradeMqtt/samples/Upgrade/.project
  Sming/Libraries/OtaUpgradeMqtt/samples/Upgrade/Makefile
  Sming/Libraries/OtaUpgradeMqtt/samples/Upgrade/README.rst
  Sming/Libraries/OtaUpgradeMqtt/samples/Upgrade/app/application.cpp
  Sming/Libraries/OtaUpgradeMqtt/samples/Upgrade/component.mk
  Sming/Libraries/OtaUpgradeMqtt/samples/Upgrade/files/certificate.pem.crt.der
  Sming/Libraries/OtaUpgradeMqtt/samples/Upgrade/files/private.pem.key.der
  Sming/Libraries/OtaUpgradeMqtt/src/AdvancedPayloadParser.cpp
  Sming/Libraries/OtaUpgradeMqtt/src/PayloadParser.cpp
  Sming/Libraries/OtaUpgradeMqtt/src/RbootPayloadParser.cpp
  Sming/Libraries/OtaUpgradeMqtt/src/include/OtaUpgrade/Mqtt/AdvancedPayloadParser.h
  Sming/Libraries/OtaUpgradeMqtt/src/include/OtaUpgrade/Mqtt/PayloadParser.h
  Sming/Libraries/OtaUpgradeMqtt/src/include/OtaUpgrade/Mqtt/RbootPayloadParser.h
  Sming/Libraries/OtaUpgradeMqtt/tools/deployer/.cproject
  Sming/Libraries/OtaUpgradeMqtt/tools/deployer/.project
  Sming/Libraries/OtaUpgradeMqtt/tools/deployer/Makefile
  Sming/Libraries/OtaUpgradeMqtt/tools/deployer/README.rst
  Sming/Libraries/OtaUpgradeMqtt/tools/deployer/app/application.cpp
  Sming/Libraries/OtaUpgradeMqtt/tools/deployer/component.mk
  docs/source/getting-started/windows/index.rst
  docs/source/index.rst
Labels: 3.5 - Approved - Waiting for CI results
