Repository SmingHub/Sming, pull requests merged in 2022-02, with the labels that each got.

#2475 Fix issue with coding style fixer failing when list of files is too long
  Sming/Makefile
  Sming/build.mk
Labels: 3 - Review

#2476 String::remove() should use memmove
  Sming/Wiring/WString.cpp
Labels: Bug, Port-to-LTS

#2477 Host fixes (RTC clock setting, UART restrictions, thread race condition)
  Sming/Arch/Host/Components/driver/component.mk
  Sming/Arch/Host/Components/driver/uart.cpp
  Sming/Arch/Host/Components/driver/uart.rst
  Sming/Arch/Host/Components/driver/uart_server.cpp
  Sming/Arch/Host/Components/esp_wifi/component.mk
  Sming/Arch/Host/Components/hostlib/options.h
  Sming/Arch/Host/Components/hostlib/threads.cpp
  Sming/Arch/Host/Components/vflash/component.mk
  Sming/Arch/Host/Platform/RTC.cpp
Labels: 3 - Review

#2478 Add CStringArray push/pop methods
  Sming/Core/Data/CStringArray.cpp
  Sming/Core/Data/CStringArray.h
  docs/source/framework/core/data/cstringarray.rst
  tests/HostTests/modules/CStringArray.cpp
Labels: 3.5 - Approved - Waiting for CI results

#2481 String::remove() should use memmove (#2476)
  Sming/Wiring/WString.cpp
Labels: 3.5 - Approved - Waiting for CI results

#2483 Fix incorrect use of assert - breaks release builds
  Sming/Arch/Esp32/Components/esp32/src/startup.cpp
  Sming/Arch/Host/Components/hostlib/threads.cpp
  Sming/Core/Data/Stream/LimitedMemoryStream.cpp
  Sming/Core/Data/Stream/MemoryDataStream.cpp
Labels: Bug, 3.5 - Approved - Waiting for CI results

#2485 Fix `ListSubDirs` build function
  Sming/Makefile
  Sming/project.mk
  Sming/util.mk
  docs/Makefile
Labels: 3.5 - Approved - Waiting for CI results

#2493 Docs: Fix issue with updated MarkupSafe.
  docs/requirements.txt
Labels: 3.5 - Approved - Waiting for CI results
